import {
  GearIcon,
  PencilIcon,
  PlusIcon,
  PlusSquareIcon,
  XIcon,
  BookmarkIcon,
  PushPinIcon,
  TrashIcon,
  DotsThreeIcon,
  ChatCircleIcon,
  ArrowsDownUpIcon,
  UserCircleIcon,
  HouseIcon,
  SlidersHorizontalIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CalendarDotIcon,
  CalendarDotsIcon,
  ArrowLineLeftIcon,
  ArrowLineRightIcon,
  CircleIcon,
  LinkIcon,
  CheckCircleIcon,
  MinusCircleIcon,
  XCircleIcon,
  ListChecksIcon,
  ArrowArcLeftIcon,
  ArrowArcRightIcon,
  PaperclipIcon,
  InfoIcon,
  NotebookIcon,
  ArrowCircleRightIcon,
  ExclamationMarkIcon,
  WarningCircleIcon,
  CaretUpIcon,
  CaretDownIcon,
  DotsThreeOutlineIcon,
  FlagBannerFoldIcon,
  ArrowUpRightIcon,
  CheckIcon,
  EmptyIcon,
  ChatCenteredTextIcon,
  EyeSlashIcon,
  EyeIcon,
} from "@phosphor-icons/react";
import type { IconType } from "./Icon.type";

export const controlIcons = [
  { name: "pushPin", component: PushPinIcon },
  { name: "bookmark", component: BookmarkIcon },
  { name: "trash", component: TrashIcon },
  { name: "pencil", component: PencilIcon },
  { name: "chatCenteredText", component: ChatCenteredTextIcon },
  { name: "x", component: XIcon, fixedWeight: "bold" },
  { name: "gear", component: GearIcon },
  { name: "plus", component: PlusIcon, fixedWeight: "regular" },
  { name: "plusSquare", component: PlusSquareIcon },
  { name: "dotsThree", component: DotsThreeIcon, fixedWeight: "bold" },
  { name: "chatCircle", component: ChatCircleIcon },
  { name: "arrowsDownUp", component: ArrowsDownUpIcon },
  { name: "house", component: HouseIcon },
  { name: "notebook", component: NotebookIcon },
  { name: "calendarDot", component: CalendarDotIcon },
  { name: "calendarDots", component: CalendarDotsIcon },
  { name: "user", component: UserCircleIcon },
  { name: "slidersHorizontal", component: SlidersHorizontalIcon },
  { name: "caretLeft", component: CaretLeftIcon },
  { name: "caretRight", component: CaretRightIcon },
  { name: "arrowLineRight", component: ArrowLineRightIcon },
  { name: "arrowLineLeft", component: ArrowLineLeftIcon },
  { name: "circle", component: CircleIcon },
  { name: "link", component: LinkIcon, fixedWeight: "regular" },
  { name: "paperclip", component: PaperclipIcon, fixedWeight: "regular" },
  { name: "checkCircle", component: CheckCircleIcon },
  { name: "check", component: CheckIcon },
  { name: "minusCircle", component: MinusCircleIcon },
  { name: "xCircle", component: XCircleIcon },
  { name: "listChecks", component: ListChecksIcon },
  { name: "arrowArcLeft", component: ArrowArcLeftIcon },
  { name: "arrowArcRight", component: ArrowArcRightIcon },
  { name: "arrowCircleRight", component: ArrowCircleRightIcon },
  { name: "info", component: InfoIcon },
  {
    name: "exclamationMark",
    component: ExclamationMarkIcon,
    fixedWeight: "regular",
  },
  { name: "warningCircle", component: WarningCircleIcon },
  { name: "caretUp", component: CaretUpIcon },
  { name: "caretDown", component: CaretDownIcon },
  {
    name: "dotsThreeOutline",
    component: DotsThreeOutlineIcon,
    fixedWeight: "fill",
  },
  { name: "flagBannerFold", component: FlagBannerFoldIcon },
  { name: "arrowUpRight", component: ArrowUpRightIcon },
  { name: "empty", component: EmptyIcon, fixedWeight: "regular" },
  { name: "eyeSlash", component: EyeSlashIcon },
  { name: "eye", component: EyeIcon },
] as const satisfies IconType[];

export type ControlIconName = (typeof controlIcons)[number]["name"];
