import {
  BookOpenIcon,
  MusicNotesSimpleIcon,
  AirplaneTiltIcon,
  PawPrintIcon,
  BarbellIcon,
  HeartIcon,
  ScrollIcon,
  BabyCarriageIcon,
  BrainIcon,
  BreadIcon,
  BriefcaseIcon,
  CameraIcon,
  CampfireIcon,
  ChefHatIcon,
  CityIcon,
  CloudIcon,
  ClubIcon,
  CodeIcon,
  CpuIcon,
  CubeIcon,
  EyeglassesIcon,
  FilmSlateIcon,
  GlobeHemisphereWestIcon,
  HouseLineIcon,
  LegoIcon,
  MartiniIcon,
  MoneyIcon,
  MaskHappyIcon,
  PaintBrushIcon,
  PenNibIcon,
  PlanetIcon,
  PottedPlantIcon,
  SailboatIcon,
  TShirtIcon,
  UsersThreeIcon,
  QuestionMarkIcon,
  LightbulbFilamentIcon,
  HammerIcon,
  ChatCircleIcon,
  PersonIcon,
  GraduationCapIcon,
  FlaskIcon,
  BlueprintIcon,
  SwatchesIcon,
  TagIcon,
  ListNumbersIcon,
  NoteBlankIcon,
  DatabaseIcon,
  CarIcon,
  CardsThreeIcon,
  DevicesIcon,
  FolderIcon,
  MathOperationsIcon,
  ShieldCheckeredIcon,
  BookmarkSimpleIcon,
  SignpostIcon,
  BugIcon,
  BinocularsIcon,
  TrayIcon,
  MagnifyingGlassIcon,
  FlagIcon,
  ListChecksIcon,
  NetworkIcon,
  ChairIcon,
  SoccerBallIcon,
  BirdIcon,
  HourglassLowIcon,
  CalendarDotsIcon,
  NotebookIcon,
  SparkleIcon,
  HandIcon,
  FlowerLotusIcon,
  DotsNineIcon,
  LockSimpleIcon,
  ArchiveIcon,
  RocketLaunchIcon,
  GameControllerIcon,
  IdentificationBadgeIcon,
  SealIcon,
  ForkKnifeIcon,
  CoffeeIcon,
  KeyIcon,
  MapPinAreaIcon,
  SunIcon,
  StorefrontIcon,
  ToiletPaperIcon,
  ArrowsClockwiseIcon,
} from "@phosphor-icons/react";
import type { IconType } from "./Icon.type";

export const customisationIcons = [
  { name: "musicNotesSimple", component: MusicNotesSimpleIcon },
  { name: "airplaneTilt", component: AirplaneTiltIcon },
  { name: "pawPrint", component: PawPrintIcon },
  { name: "barbell", component: BarbellIcon },
  { name: "soccerBall", component: SoccerBallIcon },
  { name: "heart", component: HeartIcon },
  { name: "flowerLotus", component: FlowerLotusIcon },
  { name: "paintBrush", component: PaintBrushIcon },
  { name: "money", component: MoneyIcon },
  { name: "sun", component: SunIcon },
  { name: "cloud", component: CloudIcon },
  { name: "hammer", component: HammerIcon },
  { name: "key", component: KeyIcon },
  { name: "lightbulbFilament", component: LightbulbFilamentIcon },
  { name: "toiletPaper", component: ToiletPaperIcon },
  { name: "chair", component: ChairIcon },
  { name: "car", component: CarIcon },
  { name: "houseLine", component: HouseLineIcon },
  { name: "storefront", component: StorefrontIcon },
  { name: "hand", component: HandIcon },
  { name: "brain", component: BrainIcon },
  { name: "person", component: PersonIcon },
  { name: "usersThree", component: UsersThreeIcon },
  { name: "babyCarriage", component: BabyCarriageIcon },
  { name: "lego", component: LegoIcon },
  { name: "club", component: ClubIcon },
  { name: "gameController", component: GameControllerIcon },
  { name: "campfire", component: CampfireIcon },
  { name: "shieldCheckered", component: ShieldCheckeredIcon },
  { name: "planet", component: PlanetIcon },
  { name: "rocketLaunch", component: RocketLaunchIcon },
  { name: "filmSlate", component: FilmSlateIcon },
  { name: "camera", component: CameraIcon },
  { name: "maskHappy", component: MaskHappyIcon },
  { name: "forkKnife", component: ForkKnifeIcon },
  { name: "coffee", component: CoffeeIcon },
  { name: "martini", component: MartiniIcon },
  { name: "chefHat", component: ChefHatIcon },
  { name: "bread", component: BreadIcon },
  { name: "sailboat", component: SailboatIcon },
  { name: "pottedPlant", component: PottedPlantIcon },
  { name: "bug", component: BugIcon },
  { name: "bird", component: BirdIcon },
  { name: "penNib", component: PenNibIcon },
  { name: "notebook", component: NotebookIcon },
  { name: "bookOpen", component: BookOpenIcon },
  { name: "magnifyingGlass", component: MagnifyingGlassIcon },
  { name: "eyeglasses", component: EyeglassesIcon },
  { name: "tShirt", component: TShirtIcon },
  { name: "briefcase", component: BriefcaseIcon },
  { name: "graduationCap", component: GraduationCapIcon },
  { name: "flask", component: FlaskIcon },
  { name: "hourglassLow", component: HourglassLowIcon },
  { name: "blueprint", component: BlueprintIcon },
  { name: "swatches", component: SwatchesIcon },
  { name: "signpost", component: SignpostIcon },
  { name: "mapPinArea", component: MapPinAreaIcon },
  { name: "city", component: CityIcon },
  { name: "globeHemisphereWest", component: GlobeHemisphereWestIcon },
  { name: "binoculars", component: BinocularsIcon },
  { name: "scroll", component: ScrollIcon },
  { name: "mathOperations", component: MathOperationsIcon },
  { name: "code", component: CodeIcon },
  { name: "cpu", component: CpuIcon },
  { name: "database", component: DatabaseIcon },
  { name: "network", component: NetworkIcon },
  { name: "devices", component: DevicesIcon },
  { name: "identificationBadge", component: IdentificationBadgeIcon },
  { name: "calendarDots", component: CalendarDotsIcon },
  { name: "sparkle", component: SparkleIcon },
  { name: "tag", component: TagIcon },
  { name: "lockSimple", component: LockSimpleIcon },
  { name: "bookmarkSimple", component: BookmarkSimpleIcon },
  { name: "flag", component: FlagIcon },
  { name: "seal", component: SealIcon },
  { name: "chatCircle", component: ChatCircleIcon },
  { name: "noteBlank", component: NoteBlankIcon },
  { name: "folder", component: FolderIcon },
  { name: "tray", component: TrayIcon },
  { name: "archive", component: ArchiveIcon },
  { name: "cardsThree", component: CardsThreeIcon },
  { name: "cube", component: CubeIcon },
  { name: "listNumbers", component: ListNumbersIcon },
  { name: "listChecks", component: ListChecksIcon },
  {
    name: "arrowsClockwise",
    component: ArrowsClockwiseIcon,
  },
  { name: "dotsNine", component: DotsNineIcon },
  { name: "questionMark", component: QuestionMarkIcon },
] as const satisfies IconType[];

export type CustomisationIconName = (typeof customisationIcons)[number]["name"];
