import {
  BookOpen,
  MusicNotesSimple,
  AirplaneTilt,
  PawPrint,
  Barbell,
  Heart,
  Scroll,
  BabyCarriage,
  Brain,
  Bread,
  Briefcase,
  Camera,
  Campfire,
  ChefHat,
  City,
  Cloud,
  Club,
  Code,
  Cpu,
  Cube,
  Eyeglasses,
  FilmSlate,
  GlobeHemisphereWest,
  HouseLine,
  Lego,
  Martini,
  Money,
  MaskHappy,
  PaintBrush,
  PenNib,
  Planet,
  PottedPlant,
  Sailboat,
  TShirt,
  UsersThree,
  QuestionMark,
  LightbulbFilament,
  Hammer,
  ChatCircle,
  Person,
  GraduationCap,
  Flask,
  Blueprint,
  Swatches,
  Tag,
  ListNumbers,
  NoteBlank,
  Database,
  Car,
  CardsThree,
  Devices,
  Folder,
  MathOperations,
  ShieldCheckered,
  BookmarkSimple,
  Signpost,
  Bug,
  Binoculars,
  Tray,
  MagnifyingGlass,
  Flag,
  ListChecks,
  Network,
  Chair,
  SoccerBall,
  Bird,
  HourglassLow,
  CalendarDot,
  Notebook,
  Sparkle,
  Hand,
  FlowerLotus,
  DotsNine,
  LockSimple,
  Archive,
  RocketLaunch,
  GameController,
  IdentificationBadge,
  Seal,
  ForkKnife,
  Coffee,
  Key,
  MapPinArea,
  Sun,
  Storefront,
  ToiletPaper,
} from "@phosphor-icons/react";

export const icons = [
  { name: "musicNotesSimple", icon: MusicNotesSimple },
  { name: "airplaneTilt", icon: AirplaneTilt },
  { name: "pawPrint", icon: PawPrint },
  { name: "barbell", icon: Barbell },
  { name: "soccerBall", icon: SoccerBall },
  { name: "heart", icon: Heart },
  { name: "flowerLotus", icon: FlowerLotus },
  { name: "paintBrush", icon: PaintBrush },
  { name: "money", icon: Money },
  { name: "sun", icon: Sun },
  { name: "cloud", icon: Cloud },
  { name: "hammer", icon: Hammer },
  { name: "key", icon: Key },
  { name: "lightbulbFilament", icon: LightbulbFilament },
  { name: "toiletPaper", icon: ToiletPaper },
  { name: "chair", icon: Chair },
  { name: "car", icon: Car },
  { name: "houseLine", icon: HouseLine },
  { name: "storefront", icon: Storefront },
  { name: "hand", icon: Hand },
  { name: "brain", icon: Brain },
  { name: "person", icon: Person },
  { name: "usersThree", icon: UsersThree },
  { name: "babyCarriage", icon: BabyCarriage },
  { name: "lego", icon: Lego },
  { name: "club", icon: Club },
  { name: "gameController", icon: GameController },
  { name: "campfire", icon: Campfire },
  { name: "shieldCheckered", icon: ShieldCheckered },
  { name: "planet", icon: Planet },
  { name: "rocketLaunch", icon: RocketLaunch },
  { name: "filmSlate", icon: FilmSlate },
  { name: "camera", icon: Camera },
  { name: "maskHappy", icon: MaskHappy },
  { name: "forkKnife", icon: ForkKnife },
  { name: "coffee", icon: Coffee },
  { name: "martini", icon: Martini },
  { name: "chefHat", icon: ChefHat },
  { name: "bread", icon: Bread },
  { name: "sailboat", icon: Sailboat },
  { name: "pottedPlant", icon: PottedPlant },
  { name: "bug", icon: Bug },
  { name: "bird", icon: Bird },
  { name: "PenNib", icon: PenNib },
  { name: "notebook", icon: Notebook },
  { name: "bookOpen", icon: BookOpen },
  { name: "magnifyingGlass", icon: MagnifyingGlass },
  { name: "eyeglasses", icon: Eyeglasses },
  { name: "tShirt", icon: TShirt },
  { name: "briefcase", icon: Briefcase },
  { name: "graduationCap", icon: GraduationCap },
  { name: "flask", icon: Flask },
  { name: "hourglassLow", icon: HourglassLow },
  { name: "blueprint", icon: Blueprint },
  { name: "swatches", icon: Swatches },
  { name: "signpost", icon: Signpost },
  { name: "mapPinArea", icon: MapPinArea },
  { name: "city", icon: City },
  { name: "globeHemisphereWest", icon: GlobeHemisphereWest },
  { name: "binoculars", icon: Binoculars },
  { name: "scroll", icon: Scroll },
  { name: "mathOperations", icon: MathOperations },
  { name: "code", icon: Code },
  { name: "cpu", icon: Cpu },
  { name: "database", icon: Database },
  { name: "network", icon: Network },
  { name: "devices", icon: Devices },
  { name: "identificationBadge", icon: IdentificationBadge },
  { name: "calendarDot", icon: CalendarDot },
  { name: "sparkle", icon: Sparkle },
  { name: "tag", icon: Tag },
  { name: "lockSimple", icon: LockSimple },
  { name: "bookmarkSimple", icon: BookmarkSimple },
  { name: "flag", icon: Flag },
  { name: "seal", icon: Seal },
  { name: "chatCircle", icon: ChatCircle },
  { name: "noteBlank", icon: NoteBlank },
  { name: "folder", icon: Folder },
  { name: "tray", icon: Tray },
  { name: "archive", icon: Archive },
  { name: "cardsThree", icon: CardsThree },
  { name: "cube", icon: Cube },
  { name: "listNumbers", icon: ListNumbers },
  { name: "listChecks", icon: ListChecks },
  { name: "dotsNine", icon: DotsNine },
  { name: "questionMark", icon: QuestionMark },
];
