import { ColourName } from "../colours/Colour.type";
import type { Colour } from "../colours/Colour.type";

export const colours: { [key in ColourName]: Colour } = {
  red: {
    name: ColourName.red,
    text: "text-red-400",
    background: "bg-red-400",
    border: "border-red-400",
    primary: {
      text: "text-red-500",
      textHovered: "hover:text-red-600",
      background: "bg-red-100",
      backgroundHovered: "hover:bg-red-300",
    },
    secondary: {
      textHovered: "hover:text-red-500",
      background: "bg-red-50",
      backgroundHovered: "hover:bg-red-100",
      border: "border-red-200",
    },
  },
  orange: {
    name: ColourName.orange,
    text: "text-orange-400",
    background: "bg-orange-400",
    border: "border-orange-400",
    primary: {
      text: "text-orange-500",
      textHovered: "hover:text-orange-600",
      background: "bg-orange-100",
      backgroundHovered: "hover:bg-orange-300",
    },
    secondary: {
      textHovered: "hover:text-orange-500",
      background: "bg-orange-50",
      backgroundHovered: "hover:bg-orange-100",
      border: "border-orange-200",
    },
  },
  yellow: {
    name: ColourName.yellow,
    text: "text-yellow-400",
    background: "bg-yellow-400",
    border: "border-yellow-400",
    primary: {
      text: "text-yellow-500",
      textHovered: "hover:text-yellow-600",
      background: "bg-yellow-100",
      backgroundHovered: "hover:bg-yellow-300",
    },
    secondary: {
      textHovered: "hover:text-yellow-500",
      background: "bg-yellow-50",
      backgroundHovered: "hover:bg-yellow-100",
      border: "border-yellow-200",
    },
  },
  lime: {
    name: ColourName.lime,
    text: "text-lime-400",
    background: "bg-lime-400",
    border: "border-lime-400",
    primary: {
      text: "text-lime-500",
      textHovered: "hover:text-lime-600",
      background: "bg-lime-100",
      backgroundHovered: "hover:bg-lime-300",
    },
    secondary: {
      textHovered: "hover:text-lime-500",
      background: "bg-lime-50",
      backgroundHovered: "hover:bg-lime-100",
      border: "border-lime-200",
    },
  },
  green: {
    name: ColourName.green,
    text: "text-green-400",
    background: "bg-green-400",
    border: "border-green-400",
    primary: {
      text: "text-green-500",
      textHovered: "hover:text-green-600",
      background: "bg-green-100",
      backgroundHovered: "hover:bg-green-300",
    },
    secondary: {
      textHovered: "hover:text-green-500",
      background: "bg-green-50",
      backgroundHovered: "hover:bg-green-100",
      border: "border-green-200",
    },
  },
  blue: {
    name: ColourName.blue,
    text: "text-blue-400",
    background: "bg-blue-400",
    border: "border-blue-400",
    primary: {
      text: "text-blue-500",
      textHovered: "hover:text-blue-600",
      background: "bg-blue-100",
      backgroundHovered: "hover:bg-blue-300",
    },
    secondary: {
      textHovered: "hover:text-blue-500",
      background: "bg-blue-50",
      backgroundHovered: "hover:bg-blue-100",
      border: "border-blue-200",
    },
  },
  cyan: {
    name: ColourName.cyan,
    text: "text-cyan-400",
    background: "bg-cyan-400",
    border: "border-cyan-400",
    primary: {
      text: "text-cyan-500",
      textHovered: "hover:text-cyan-600",
      background: "bg-cyan-100",
      backgroundHovered: "hover:bg-cyan-300",
    },
    secondary: {
      textHovered: "hover:text-cyan-500",
      background: "bg-cyan-50",
      backgroundHovered: "hover:bg-cyan-100",
      border: "border-cyan-200",
    },
  },
  pink: {
    name: ColourName.pink,
    text: "text-pink-400",
    background: "bg-pink-400",
    border: "border-pink-400",
    primary: {
      text: "text-pink-500",
      textHovered: "hover:text-pink-600",
      background: "bg-pink-100",
      backgroundHovered: "hover:bg-pink-300",
    },
    secondary: {
      textHovered: "hover:text-pink-500",
      background: "bg-pink-50",
      backgroundHovered: "hover:bg-pink-100",
      border: "border-pink-200",
    },
  },
  purple: {
    name: ColourName.purple,
    text: "text-purple-400",
    background: "bg-purple-400",
    border: "border-purple-400",
    primary: {
      text: "text-purple-500",
      textHovered: "hover:text-purple-600",
      background: "bg-purple-100",
      backgroundHovered: "hover:bg-purple-300",
    },
    secondary: {
      textHovered: "hover:text-purple-500",
      background: "bg-purple-50",
      backgroundHovered: "hover:bg-purple-100",
      border: "border-purple-200",
    },
  },
  brown: {
    name: ColourName.brown,
    text: "text-amber-600",
    background: "bg-amber-600",
    border: "border-brown-400",
    primary: {
      text: "text-amber-700",
      textHovered: "hover:text-amber-600",
      background: "bg-amber-200",
      backgroundHovered: "hover:bg-amber-300",
    },
    secondary: {
      textHovered: "hover:text-amber-700",
      background: "bg-amber-50",
      backgroundHovered: "hover:bg-amber-200",
      border: "border-brown-300",
    },
  },
  grey: {
    name: ColourName.grey,
    text: "text-gray-400",
    background: "bg-gray-400",
    border: "border-gray-400",
    primary: {
      text: "text-gray-500",
      textHovered: "hover:text-gray-600",
      background: "bg-gray-100",
      backgroundHovered: "hover:bg-gray-200",
    },
    secondary: {
      textHovered: "hover:text-gray-500",
      background: "bg-gray-100",
      backgroundHovered: "hover:bg-gray-100",
      border: "border-gray-200",
    },
  },
};
