/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as CreatePocketbookRouteImport } from './routes/create-pocketbook'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutPocketbookIdBookmarkedRouteImport } from './routes/_layout.$pocketbookId.bookmarked'
import { Route as LayoutPocketbookIdNotesRouteImport } from './routes/_layout.$pocketbookId.notes'
import { Route as LayoutPocketbookIdPlannerRouteImport } from './routes/_layout.$pocketbookId.planner'
import { Route as LayoutPocketbookIdTasksRouteImport } from './routes/_layout.$pocketbookId.tasks'
import { Route as LayoutPocketbookIdTagsTagIdRouteImport } from './routes/_layout.$pocketbookId.tags.$tagId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePocketbookRoute = CreatePocketbookRouteImport.update({
  id: '/create-pocketbook',
  path: '/create-pocketbook',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPocketbookIdBookmarkedRoute =
  LayoutPocketbookIdBookmarkedRouteImport.update({
    id: '/$pocketbookId/bookmarked',
    path: '/$pocketbookId/bookmarked',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPocketbookIdNotesRoute = LayoutPocketbookIdNotesRouteImport.update({
  id: '/$pocketbookId/notes',
  path: '/$pocketbookId/notes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPocketbookIdPlannerRoute =
  LayoutPocketbookIdPlannerRouteImport.update({
    id: '/$pocketbookId/planner',
    path: '/$pocketbookId/planner',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPocketbookIdTasksRoute = LayoutPocketbookIdTasksRouteImport.update({
  id: '/$pocketbookId/tasks',
  path: '/$pocketbookId/tasks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPocketbookIdTagsTagIdRoute =
  LayoutPocketbookIdTagsTagIdRouteImport.update({
    id: '/$pocketbookId/tags/$tagId',
    path: '/$pocketbookId/tags/$tagId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutRouteWithChildren
  '/create-pocketbook': typeof CreatePocketbookRoute
  '/login': typeof LoginRoute
  '/$pocketbookId/bookmarked': typeof LayoutPocketbookIdBookmarkedRoute
  '/$pocketbookId/notes': typeof LayoutPocketbookIdNotesRoute
  '/$pocketbookId/planner': typeof LayoutPocketbookIdPlannerRoute
  '/$pocketbookId/tasks': typeof LayoutPocketbookIdTasksRoute
  '/$pocketbookId/tags/$tagId': typeof LayoutPocketbookIdTagsTagIdRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutRouteWithChildren
  '/create-pocketbook': typeof CreatePocketbookRoute
  '/login': typeof LoginRoute
  '/$pocketbookId/bookmarked': typeof LayoutPocketbookIdBookmarkedRoute
  '/$pocketbookId/notes': typeof LayoutPocketbookIdNotesRoute
  '/$pocketbookId/planner': typeof LayoutPocketbookIdPlannerRoute
  '/$pocketbookId/tasks': typeof LayoutPocketbookIdTasksRoute
  '/$pocketbookId/tags/$tagId': typeof LayoutPocketbookIdTagsTagIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/create-pocketbook': typeof CreatePocketbookRoute
  '/login': typeof LoginRoute
  '/_layout/$pocketbookId/bookmarked': typeof LayoutPocketbookIdBookmarkedRoute
  '/_layout/$pocketbookId/notes': typeof LayoutPocketbookIdNotesRoute
  '/_layout/$pocketbookId/planner': typeof LayoutPocketbookIdPlannerRoute
  '/_layout/$pocketbookId/tasks': typeof LayoutPocketbookIdTasksRoute
  '/_layout/$pocketbookId/tags/$tagId': typeof LayoutPocketbookIdTagsTagIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-pocketbook'
    | '/login'
    | '/$pocketbookId/bookmarked'
    | '/$pocketbookId/notes'
    | '/$pocketbookId/planner'
    | '/$pocketbookId/tasks'
    | '/$pocketbookId/tags/$tagId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-pocketbook'
    | '/login'
    | '/$pocketbookId/bookmarked'
    | '/$pocketbookId/notes'
    | '/$pocketbookId/planner'
    | '/$pocketbookId/tasks'
    | '/$pocketbookId/tags/$tagId'
  id:
    | '__root__'
    | '/_layout'
    | '/create-pocketbook'
    | '/login'
    | '/_layout/$pocketbookId/bookmarked'
    | '/_layout/$pocketbookId/notes'
    | '/_layout/$pocketbookId/planner'
    | '/_layout/$pocketbookId/tasks'
    | '/_layout/$pocketbookId/tags/$tagId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  CreatePocketbookRoute: typeof CreatePocketbookRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-pocketbook': {
      id: '/create-pocketbook'
      path: '/create-pocketbook'
      fullPath: '/create-pocketbook'
      preLoaderRoute: typeof CreatePocketbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/$pocketbookId/bookmarked': {
      id: '/_layout/$pocketbookId/bookmarked'
      path: '/$pocketbookId/bookmarked'
      fullPath: '/$pocketbookId/bookmarked'
      preLoaderRoute: typeof LayoutPocketbookIdBookmarkedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$pocketbookId/notes': {
      id: '/_layout/$pocketbookId/notes'
      path: '/$pocketbookId/notes'
      fullPath: '/$pocketbookId/notes'
      preLoaderRoute: typeof LayoutPocketbookIdNotesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$pocketbookId/planner': {
      id: '/_layout/$pocketbookId/planner'
      path: '/$pocketbookId/planner'
      fullPath: '/$pocketbookId/planner'
      preLoaderRoute: typeof LayoutPocketbookIdPlannerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$pocketbookId/tasks': {
      id: '/_layout/$pocketbookId/tasks'
      path: '/$pocketbookId/tasks'
      fullPath: '/$pocketbookId/tasks'
      preLoaderRoute: typeof LayoutPocketbookIdTasksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$pocketbookId/tags/$tagId': {
      id: '/_layout/$pocketbookId/tags/$tagId'
      path: '/$pocketbookId/tags/$tagId'
      fullPath: '/$pocketbookId/tags/$tagId'
      preLoaderRoute: typeof LayoutPocketbookIdTagsTagIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutPocketbookIdBookmarkedRoute: typeof LayoutPocketbookIdBookmarkedRoute
  LayoutPocketbookIdNotesRoute: typeof LayoutPocketbookIdNotesRoute
  LayoutPocketbookIdPlannerRoute: typeof LayoutPocketbookIdPlannerRoute
  LayoutPocketbookIdTasksRoute: typeof LayoutPocketbookIdTasksRoute
  LayoutPocketbookIdTagsTagIdRoute: typeof LayoutPocketbookIdTagsTagIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutPocketbookIdBookmarkedRoute: LayoutPocketbookIdBookmarkedRoute,
  LayoutPocketbookIdNotesRoute: LayoutPocketbookIdNotesRoute,
  LayoutPocketbookIdPlannerRoute: LayoutPocketbookIdPlannerRoute,
  LayoutPocketbookIdTasksRoute: LayoutPocketbookIdTasksRoute,
  LayoutPocketbookIdTagsTagIdRoute: LayoutPocketbookIdTagsTagIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  CreatePocketbookRoute: CreatePocketbookRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
